package main

import (
	"fmt"
	mr "mapreduce"
	"strconv"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input. In this
// framework, the key is the name of the file that is being processed, and the
// value is the file's contents. The return value should be a slice of key/value
// pairs, each represented by a mapreduce.KeyValue.
func mapF(fileName string, contents string) (res []mr.KeyValue) {
	words := strings.FieldsFunc(contents, func(c rune) bool { return !unicode.IsLetter(c) })
	wordCount := make(map[string]int)

	for _, word := range words {
		wordCount[word]++
	}

	for word, count := range wordCount {
		res = append(res, mr.KeyValue{word, strconv.Itoa(count)})
	}
	return
}

// The reduce function is called once for each key generated by Map, with a list
// of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	var count int64
	for _, value := range values {
		x, err := strconv.ParseInt(value, 10, 64)
		if err != nil {
			fmt.Errorf("Failed parsed integer: %s\n", value)
			continue
		}
		count += x
	}
	return strconv.FormatInt(count, 10)
}

// Parses the command line arguments and runs the computation. "Running the
// computation" could mean that this node is a worker or a master, depending on
// the command line flags. See `mr/parse_cmd_line.go:parseCmdLine` for details.
func main() {
	mr.Run("wordcount", mapF, reduceF)
}
