package main

import (
	"bytes"
	"fmt"
	mr "mapreduce"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input. In this
// framework, the key is the name of the file that is being processed, and the
// value is the file's contents. The return value should be a slice of key/value
// pairs, each represented by a mapreduce.KeyValue.
func mapF(fileName string, contents string) (res []mr.KeyValue) {
	words := strings.FieldsFunc(contents, func(c rune) bool { return !unicode.IsLetter(c) })
	wordMap := make(map[string]bool)

	for _, word := range words {
		wordMap[word] = true
	}

	for word, _ := range wordMap {
		res = append(res, mr.KeyValue{word, fileName})
	}
	return
}

// The reduce function is called once for each key generated by Map, with a list
// of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// FIXME: Implement me.
	var count int
	var buffer bytes.Buffer
	for _, file := range values {
		count++
		buffer.WriteString(file)
		buffer.WriteString(",")
	}

	//remove the trailing ,
	return fmt.Sprintf("%d %s", count, strings.TrimSuffix(buffer.String(), ","))
}

// Parses the command line arguments and runs the computation. "Running the
// computation" could mean that this node is a worker or a master, depending on
// the command line flags. See `mr/parse_cmd_line.go:parseCmdLine` for details.
func main() {
	mr.Run("invertedindex", mapF, reduceF)
}
